name: cpd_assignment
description: Cross Platform Development Assignment - Task Manager App with Provider and SharedPreferences
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Location
  geolocator: ^11.0.0

  # UI Components
  cupertino_icons: ^1.0.6

  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
